### ISSUE TITLE
Update to 0.4.13

### ISSUE THREAD

**Issue by Windfisch** [ros-noetic-arch/ros-noetic-rqt-bag#1]
Hi @acxz,

the version 0.4.12 which is shipped in the AUR of the rqt_bag package has an issue where loading a file causes an `TypeError: 'filter' object is not subscriptable` error. This is fixed upstream in 0.4.13, which belongs to the official ROS noetic distro as of https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml .

However, I am not sure how to update the PKGBUILD. Shall I just file a PR which updates to the new version, or do you have this automated and just need to execute a script? If that's the case: please execute that script ;)

Best regards,
Windfisch

**Comment by acxz** [comment]
Hello @Windfisch our upgrade process is not yet automated yet. See the [ros-arch](https://github.com/ros-arch) org for progress on that.

I currently don't have the bandwidth to work on this myself and would really appreciate a PR.

As for updating the PKGBUILD, it's pretty simple. Take a look at past PRs that have occurred in this organization for concrete examples.
Things to do:
1. Update the `pkgver` field
2. Update the `sha256sums` by running `sha256sum ***.tar.gz` where `***.tar.gz` is the latest github release.
3. Update the `.SRCINFO` by running `makepkg --printsrcinfo > .SRCINFO`

You can see more information on this on the ArchWiki pages of `PKGBUILD`, `SRCINFO` and `makepkg`.

Commit those changes and send a PR to this repo and I'll merge it ASAP.

**Comment by Windfisch** [comment]
Good to know, in that case I will submit one or another PR soon! I'm closing this issue when I made the commit.

Thanks for your work on these PKGBUILDs :)

**Comment by acxz** [comment]
@Windfisch since it has been a week, I went ahead and updated the package myself, thx for reporting.

**Comment by Windfisch** [comment]
aww, sorry, I still had that around on my to do list :D. Thank you for updating it! :)
